spring:
  cloud:
    stream:
      bindings:
        # 1. Cambiamos el nombre para que coincida con el Controller
        enviarOrden-out-0: 
          destination: exchange.ordenes.fanout # El nombre del "repartidor"
      rabbit:
        bindings:
          enviarOrden-out-0:
            producer:
              # 2. LA CLAVE: Declaramos que es un Fanout (Multicast)
              exchangeType: fanout 
              # En Fanout no necesitamos routing-key porque le llega a TODOS
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest