services:
  traefik:
    image: traefik:v3.0
    container_name: traefik-balancer
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false" # Por seguridad, solo balancea lo que le digamos
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"       # Tráfico que llegará a tu API
      - "8080:8080"   # Dashboard para que veas qué está pasando
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  # Nuestro "Hola Mundo" (Simulando tu futura API Handler)
  api-test:
    image: traefik/whoami
    deploy:
      replicas: 2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-test.rule=Host(`localhost`)" # O la IP de tu server
      - "traefik.http.services.api-test.loadbalancer.server.port=80"